### ISSUE TITLE
PlaceTradeTDA.m

### ISSUE THREAD

**Issue by yeomaja** [nvanhart/TDA_API#1]
Was looking at your code and if you haven't identified the issue yet, you need to add one line to your script after your definition of body.

body.orderLegCollection = {body.orderLegCollection};

The orderLegCollection needs to be in [ ] for the postData and the above line gets them added.

Thanks,
John

**Comment by nvanhart** [comment]
Hi John,

Thanks for this update - looks like I uploaded an outdated version.
Appreciate your catch.

Noah

**Comment by nvanhart** [comment]
Hi John,

Added four more specific variations of the PlaceTradeTDA.m script. Thanks again for the catch.

Noah
